# Default values for gitlab-code-review-notifier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gitlab-code-review-notifier
  pullPolicy: IfNotPresent

#imagePullSecrets:
#  - name: gitlab-code-review-notifier-registry
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

gitlabUrl: "https://gitlab"
timeZone: Europe/Moscow
workdayStartAtHour: 10
workdayEndAtHour: 19
schedulerIntervalMinutes: 0
schedulerFixedTimes: "10:00:00; 13:00:00; 16:00:00; 18:00:00;"

# DB
postgresql:
  enabled: true
  host:
#  service:
#    port: 5432
  postgresqlDatabase: gitlab-code-review-notifier
  postgresqlUsername: user
#  postgresqlPassword:
#  existingSecret:
  persistence:
    enabled: true
    size: 1Gi
